import {
  fastAccordion,
  fastAccordionItem,
  fastAnchor,
  fastAvatar,
  fastAnchoredRegion,
  fastBadge,
  fastBreadcrumb,
  fastBreadcrumbItem,
  // fastButton,
  fastCalendar,
  fastCard,
  fastDivider,
  fastFlipper,
  fastListbox,
  fastMenu,
  fastMenuItem,
  fastNumberField,
  fastProgressRing,
  fastRadioGroup,
  fastSlider,
  fastSwitch,
  fastCheckbox,
  fastCombobox,
  fastDataGrid,
  fastDataGridCell,
  fastDataGridRow,
  fastDesignSystemProvider,
  fastDialog,
  fastDisclosure,
  fastHorizontalScroll,
  fastOption,
  fastPicker,
  fastPickerList,
  fastPickerListItem,
  fastPickerMenu,
  fastPickerMenuOption,
  fastProgress,
  fastRadio,
  fastSearch,
  fastSelect,
  fastSkeleton,
  fastSliderLabel,
  fastTab,
  fastTabPanel,
  fastTabs,
  fastTextArea,
  fastTextField,
  fastToolbar,
  fastTooltip,
  fastTreeItem,
  fastTreeView,
  provideFASTDesignSystem,
} from "@microsoft/fast-components";
import {
  demoButton,
  demoCard,
  demoAttribution,
  demoSidebar,
} from "./components";

provideFASTDesignSystem().withPrefix("example").register(
  demoSidebar(),
  demoButton(),
  demoAttribution(),
  demoCard(),

  fastAccordion(),
  fastAccordionItem(),
  fastAnchor(),
  fastAvatar(),
  fastAnchoredRegion(),
  fastBadge(),
  fastBreadcrumb(),
  fastBreadcrumbItem(),
  // fastButton(),
  fastCalendar(),
  fastCard(),
  fastDivider(),
  fastFlipper(),
  fastListbox(),
  fastMenu(),
  fastMenuItem(),
  fastNumberField(),
  fastProgressRing(),
  fastRadioGroup(),
  fastSlider(),
  fastSwitch(),
  fastCheckbox(),
  fastCombobox(),
  fastDataGrid(),
  fastDataGridCell(),
  fastDataGridRow(),
  fastDesignSystemProvider(),
  fastDialog(),
  fastDisclosure(),
  fastHorizontalScroll(),
  fastOption(),
  fastPicker(),
  fastPickerList(),
  fastPickerListItem(),
  fastPickerMenu(),
  fastPickerMenuOption(),
  fastProgress(),
  fastRadio(),
  fastSearch(),
  fastSelect(),
  fastSkeleton(),
  fastSliderLabel(),
  fastTab(),
  fastTabPanel(),
  fastTabs(),
  fastTextArea(),
  fastTextField(),
  fastToolbar(),
  fastTooltip(),
  fastTreeItem(),
  fastTreeView()
);

/**
 * Change as many tokens as you need to get the effect you want.
 * Uncomment the code below to change defaults and sections in various ways.
 */

// controlCornerRadius.withDefault(20);
// density.withDefault(4);
// neutralPalette.withDefault(
//   PaletteRGB.create(SwatchRGB.from(parseColorHexRGB("#0078D4")!))
// );
// baseLayerLuminance.withDefault(StandardLuminance.DarkMode);
